; Script generated by Inno Setup Script Wizard.
; Facebook Notification & Scraper Installer Script

#define MyAppName "Facebook Notification & Scraper"

#ifndef MyAppVersion
  #if FileExists(AddBackslash(SourcePath) + "..\.version")
    #define FileHandle FileOpen(AddBackslash(SourcePath) + "..\.version")
    #define MyAppVersion Trim(FileRead(FileHandle))
    #expr FileClose(FileHandle)
  #else
    #define MyAppVersion "1.0.1"
  #endif
#endif

#define MyAppPublisher "PhuongDev"
#define MyAppURL "https://gitlab.com/phuongdev89/facebook_post_comment_scraper"
#define MyAppExeName "FacebookNotification.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
AppId={{8E47D63A-9F22-4D39-9B9B-89A82D6E3F41}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\FacebookNotification
DefaultGroupName={#MyAppName}
AllowNoIcons=yes

; Output directly to the dist/ directory
OutputDir=..\dist
OutputBaseFilename=FacebookNotification_Setup_v{#MyAppVersion}
SetupIconFile=..\assets\icon.ico
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
ArchitecturesInstallIn64BitMode=x64compatible

; Permissions & Pages
PrivilegesRequiredOverridesAllowed=dialog commandline
PrivilegesRequired=lowest
DisableProgramGroupPage=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Files]
Source: "..\dist\FacebookNotification\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\dist\FacebookNotification\_internal\*"; DestDir: "{app}\_internal"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\assets\*"; DestDir: "{app}\assets"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\guides\*"; DestDir: "{app}\guides"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\.version"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\.version"; DestDir: "{app}\_internal"; Flags: ignoreversion

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\assets\icon.ico"
Name: "{group}\Hướng dẫn sử dụng"; Filename: "{app}\guides\index.html"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\assets\icon.ico"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
